apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio-deployment
  labels:
    app: my-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
      # --- Container 1: Your Nginx Application ---
      - name: my-portfolio
        image: fatmaa23/my-portfolio:latest # This will be replaced by Jenkins
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

      # --- Container 2: The Nginx Exporter Sidecar (Corrected) ---
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        # *** THIS IS THE FIX ***
        # We are now explicitly telling the container which command to run,
        # which avoids any errors from the default entrypoint script.
        command: ["/usr/bin/nginx-prometheus-exporter"]
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/stub_status"
        ports:
        - containerPort: 9113

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config