apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio-deployment
  labels:
    app: my-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: my-portfolio
        image: fatmaa23/my-portfolio:build-77
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

      # --- Container 2: The Nginx Exporter Sidecar (Final Fix) ---
      - name: nginx-exporter
        image: fatmaa23/my-portfolio:build-77
        # *** THIS IS THE FIX ***
        # We are removing the 'command' line completely.
        # The default entrypoint of the image is smart enough to handle the args.
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/stub_status"
        ports:
        - containerPort: 9113

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config